on: push

name: build and test app
on:	
  pull_request:	
    branches:	
      - development	
      - master	

jobs:	jobs:
  test:	  build:
    name: Flutter Tests	    name: install dependencies
    runs-on: ubuntu-latest	    runs-on: ubuntu-latest

    steps:	    steps:
      - uses: actions/checkout@v1	    - uses: actions/checkout@v1
      - uses: actions/setup-java@v1	
        with:	    - name: install dependencies
          java-version: '12.x'	      uses: steebchen/flutter@v1.0.0
      - uses: subosito/flutter-action@v1	      with:
        with:	        args: pub get
          flutter-version: '1.7.8+hotfix.4'	
      - run: flutter doctor	    - name: run tests
      - run: flutter pub get	      uses: steebchen/flutter@v1.0.0
      - run: flutter test	      with:
        args: test

    - name: build apk
      uses: steebchen/flutter@v1.0.0
      with:
        args: build apk --release